### ISSUE TITLE
color scheme file commentary clarification

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/CSS_core#12]
In the color scheme files, such as
https://github.com/PreTeXtBook/CSS_core/blob/master/colors_blue_red.css

I am confused by the commentary. There is 1), 2), and 3). Then later there is 3) and 4). Normally I would assume that the latter 3) and 4) were supposed to be 4) and 5). But it may be that the latter 3) is supposed to match the earlier 3).

**Comment by davidfarmer** [comment]
Yes, those should be 4) and 5), and the other explanations also
need work.

Probably I should put the correct documentation in colors_default.css
and then point the others to that file.  Otherwise the cause of this
problem will keep reappearing (that is, you keep copying file to file,
so out-of-date stuff goes along for the ride).

**Comment by Alex-Jordan** [comment]
OK, thanks. If that moves to a central place, then I have some questions that could maybe be answered in that same place.

1. Are there any requirements on differences/ratios between 'documenttitle', 'bodytitle', and 'bodysubtitle'? Aesthetics aside, could they all be the same thing? Do they need some contrast ratio between them?

2. Could there be a short (not necessarily comprehensive) list of things colored by these colors? For example, I think I discern that knowl links use the "bodytitle" color.

**Comment by Alex-Jordan** [comment]
Please disregard my last two questions, as I think I have worked that all out now. But I am having trouble with this from the comments:

```
     /*
       The bodytitle and bodysubtitle colors must have at least a 3:1 contrast
       ratio with black, and at least 5:1 ratio with with the corresponding highlight.
       (The second condition will guarantee an adequate contrast with white.)
     */
```
My question, if you can bear with my thought process below, is: am I overlooking something important?

I assume that from dark to light, the arrangement is black->bodytitle->bodytitlehighlight->white. If (bodytitle,black) has a contrast ratio of at least 3:1, and (bodytitlehighlight,bodytitle) has a contrast ratio of at least 5:1, then (bodytitlehighlight,black) has a contrast ratio of at least 15:1. Then (bodytitlehighlight,white) has a contrast ratio of _at most_ 21:15, or 1.4:1. So I do not understand the bit about guaranteeing adequate contrast with white. But I don't even think contrast with white is required.

I think I understand that (aside from the TOC), documenttitle, bodytitle, and bodysubtitle are used as (dark) text colors, with bodytitlehighlight and bodysubtitlehighlight as corresponding (light) background colors (and also as the background to a "part" in the TOC). bodytitle and bodysubtitle might be used to color a true link, and PTX is not underlining true links. Therefore these need to have ratio at least 3:1 with black.

Then WCAG says the two lighter colors need ratio at least 4.5:1 with their dark counterparts. There is no need for any ratio with white. 

So am I missing something important?

**Comment by davidfarmer** [comment]
This may be an example of incorrect comments being worse than no comments.

What I may have meant is that you need contrast with white or else you
can't actually see that highlighting has occurred.

Looks like I need to continue refactoring the CSS.

**Comment by Alex-Jordan** [comment]
Well, the good news is that I can help now. I took a dive into it to understand how I could design "better" colors for ORCCA, and consequently I understand how it works now. I have some ideas, but I'm not sure what venue is best to discuss them. Related, I believe I uncovered some issues with colors and CSS that are not a part of the colors....css files.

**Comment by davidfarmer** [comment]
Let's discuss on -dev .

On a slightly related note, I am about to start a discussion that
shoudl lead to developing additional HTML styles.
