### ISSUE TITLE
Fonts in figure captions/table titles

### ISSUE THREAD

**Issue by mitchkeller** [PreTeXtBook/CSS_core#18]
`pretext_add_on.css` is not using PT Serif on the word "Figure" or "Table" in the caption/title of a figure or table, so we get this odd sans serif type, serif codenumber, sans serif caption/title text. It appears that the CSS selectors that style `type` as PT Serif in other contexts have an h6 heading involved, but that doesn't happen inside things like figcaption.

**Comment by davidfarmer** [comment]
This should be fixed now.  Please check.

**Comment by mitchkeller** [comment]
Yes, this is now fixed for projects using 0.31 for the CSS version. We will have things ready for Active Calculus to have new builds by mid-August, so that should fix things. Thanks!
