### ISSUE TITLE
Some oscarlevin issues

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/CSS_core#24]
Keeping track of things while completing the oscarlevin style.

1.  Lemmas/propositions (where are some examples?)
2. Corollaries (confirm that this looks as desired: https://pretextbook.org/examples/sample-article/oscar/interesting-corollary.html#ghI)
3. Objectives (https://pretextbook.org/examples/sample-article/oscar/interesting-corollary.html) .  Similar for Outcomes:  https://pretextbook.org/examples/sample-article/oscar/interesting-corollary.html#outcomes-structures
4. Knowled example has a "long" L.  As desired? https://pretextbook.org/examples/sample-article/oscar/interesting-corollary.html#mNo

6. Should "Note" have a different style?  https://pretextbook.org/examples/sample-article/oscar/interesting-corollary.html#note-remark
7. Is the contrast between theorem title and background adequate?  https://pretextbook.org/examples/sample-article/oscar/section-fundamental-theorem.html#theorem-FTC
8. "Remark" style?  https://pretextbook.org/examples/sample-article/oscar/section-5.html#remark-1
9. Figure captions?  https://pretextbook.org/examples/sample-article/oscar/section-5.html#figure-function-derivative

**Comment by davidfarmer** [comment]
Warning:  https://pretextbook.org/examples/sample-article/oscar/text-in-paragraphs.html#warning-1

Should exercises sections have a different style? https://pretextbook.org/examples/sample-article/oscar/section-11.html

Contrast with definition heading:  https://pretextbook.org/examples/sample-article/oscar/lists.html#definition-2
And assemblage: https://pretextbook.org/examples/sample-article/oscar/lists.html#math-list-test

List: https://pretextbook.org/examples/sample-article/oscar/lists.html#list-1
Table: https://pretextbook.org/examples/sample-article/oscar/table-calisthenics.html#table-11
Listing: https://pretextbook.org/examples/sample-article/oscar/section-programs.html#console-raspberry-pi-multi

Error:  Corollary inside knowl (open first knowl) https://pretextbook.org/examples/sample-article/oscar/section-cross-referencing.html#p-834
Similar error:  https://pretextbook.org/examples/sample-article/oscar/section-cross-referencing.html#p-838
Also see knowl 4.9 (Note)  https://pretextbook.org/examples/sample-article/oscar/section-cross-referencing.html#p-840
and other nearby knowls

Algorithm looks good, but confirm it is as intended: https://pretextbook.org/examples/sample-article/oscar/section-programs.html#algorithm-sieve-eratosthenes

Commentary: https://pretextbook.org/examples/sample-article/html/ancillaries.html#commentary-1

**Comment by oscarlevin** [comment]
These are all good things to check, but it seems that you have the old version of the style_oscarlevin.css loading on the sample article right now, not the one from the pull request sent Sunday.

**Comment by oscarlevin** [comment]
How do I style knowls that contain theorems (for example) different from theorems?  At one point I was only styling theorems if they are in `section article`, but then when they were in paragraphs, they didn't get styled (I think).

**Comment by davidfarmer** [comment]
probably obsolete
