### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/CSS_core#42]
The main two CSS files do not pass validation:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fpretextbook.org%2Fcss%2F0.4%2Fpretext.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fpretextbook.org%2Fcss%2F0.4%2Fpretext_add_on.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

(banner_default, toc_default, knowls_default, style_default, set_colors, and colors_blue_red all pass validation [I did not check other color files])

Low hanging fruit for a new contributor to work on those two?

Those files aside, with the overhaul that is underway, we should check that new CSS files validate.

**Comment by davidfarmer** [comment]
Fixed in the overhaul branch.

I'll make a new issue to check the css coming from React.
