### ISSUE TITLE
The search results popup is obscured by the top navbar and the page footer

### ISSUE THREAD

**Issue by christianp** [PreTeXtBook/CSS_core#48]
Here's an image showing the search results bar rendered underneath `#ptx-navbar` and `.ptx-page-footer`:

![image](https://user-images.githubusercontent.com/19513/208703856-9f43aa58-a281-46e9-b89d-35f955c3c2dd.png)

While `#searchresultsplaceholder` has `z-index: 5000`, its parent `#ptx-masthead` has `z-index: 100`, so forms a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

`#ptx-navbar` has `z-index: 200`, so overlaps everything in the masthead. `.ptx-page-footer` has `z-index: 100` and occurs after the masthead, so is rendered above it.

It's not clear to me why the search results element needs to be a child of the masthead. It could be a child of `<body>`. It could also do with an ARIA role of something like `dialog`.

**Comment by davidfarmer** [comment]
Sorry, I messed that up when I was experimenting with some suggestions
about the TOC, and forgot to revert it.

Should be fixed if you reload.

**Comment by christianp** [comment]
It doesn't appear under the navbar any more, but it's still under the page footer.

**Comment by davidfarmer** [comment]
Thanks.  Fixed.

**Comment by christianp** [comment]
Thanks!
