### ISSUE TITLE
Some design considerations: "overflowing math", 

### ISSUE THREAD

**Issue by bohrium2b** [PreTeXtBook/CSS_core#51]
Right now, if you go to the sample book, a very small amount of the total screen space is being used.
![image](https://user-images.githubusercontent.com/85321730/210285522-8faae920-0800-4115-a18d-b3f086df968f.png)
This space is just white, when content could be expanded to occupy that area. Also, the footer takes up a ridiculous amount of space on the bottom of the screen. It is also not fully taking up the whole bottom of the screen. Subsection numbers aren't appearing (while I think some would appreciate it, especially when references are made to, say, Section 48.2.1, which causes users to get confused trying to find 48, 2, and 1 in the table of contents). 

Suggestions:

 * Move the content into the middle, keep the table of contents at the edge and find something to occupy the right side. 
 * expand the navbar (top and bottom) to occupy the whole screen

**Comment by davidfarmer** [comment]
The CRC style centers the text, so please see if you prefer that to the default.

Our previous attempts to put more numbers on the TOC did not look good.  A mockup could help, if you have a suggestion.

The footer takes up as much space as it takes up.  If you scroll up, then the footer slides down and more text is visible.  So, it is not clear how making the footer smaller would gain anything.

Discussion about specific layout issues should occur on the pretext-support or pretext-dev Google groups, before being submitted as GitHub issues.

**Comment by davidfarmer** [comment]
If "content could be expanded to occupy that area" refers to making the lines longer, that is not a good option because long lines are difficult to read.
